apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  creationTimestamp: null
  name: fairwinds-stable
  namespace: flux-system
spec:
  interval: 1m0s
  type: default
  url: https://charts.fairwinds.com/stable
status: {}
