apiVersion: kustomize.config.k8s.io/v1beta1
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
metadata:
  name: helm-root
  namespace: flux-system
resources:
- src/release-flux-giantswarm.yaml
- src/repository-flux-app.yaml
- src/values/flux-system-flux-giantswarm-values.flux-aws.yaml
- src/values/flux-system-flux-giantswarm-values.flux.yaml
